TARGET     = 
MODE       = bin
STACKSIZE  = 64k
MALLOCSIZE = 256k
MMAREA     = 0
OBJS       = $(TARGET).obj

INCPATH    = ../z_tools/guigui00/
CC1OPT     =
BIMOPT0    = -v48a
BIMOPT1    = -tek5 clv:5 eopt: eprm:

ARCFLIES   =
ARCORG     =
ARCTEK     =
BIMOPT2    =

include ../z_tools/com_mak.txt

# 通过重写#OBJS 支持拆分编译

# tolset08対応Makefile
